### ISSUE TITLE
Create project landing page

### ISSUE THREAD

**Issue by F1R3BLAZ3** [F1R3BLAZ3/Paws-Purrs#9]
The goal of this task is to create an engaging and informative landing page for your project. This page should provide an overview of the project, highlight its features, and guide users on how to use the website.

**Comment by DuncanMoyo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create project landing page](https://trello.com/c/TPnw30J1/4-create-project-landing-page)
